// Generated by Wrangler on Tue Feb 04 2025 12:16:47 GMT-0500 (Eastern Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	AUTH_SECRET: string;
	DATABASE: D1Database;
}
