name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "testing"
database_id = "437e9e1b-f78c-40a6-9747-909f9c71e928"
migrations_dir = "./drizzle"

[build]
command = "npm run build"
